<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class TalkieTTS {
	private $talkie_tts_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'talkie_tts_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'talkie_tts_page_init' ) );
	}

	public function talkie_tts_add_plugin_page() {
		
		$icon = file_get_contents(plugins_url( '/images/icon.svg', __FILE__ ));
		
		add_menu_page(
			'Talkie Text to Speech', // page_title
			'Talkie TTS', // menu_title
			'manage_options', // capability
			'talkie-tts', // menu_slug
			array( $this, 'talkie_tts_create_admin_page' ), // function
			 'data:image/svg+xml;base64,' . base64_encode( $icon ), // icon_url 
		);
	}
	
	public function talkie_tts_create_admin_page() {
		$this->talkie_tts_options = get_option( 'talkie_tts_option_name' ); ?>

		<div class="wrap">
			<h2>Talkie Text to Speech</h2>
			
			  <p>Talkie is a simple text to speech plugin for your website. The vistors of your website can text on your page translate to speech in multiple languages. Talkie is also available as iPhone and Android application. You can download the app in the <a href="https://itunes.apple.com/nl/app/talkie/id1156128552?mt=8" target="_blank">App Store</a> or <a href="https://play.google.com/store/apps/details?id=nl.tribble.talkie&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-" target="_blank">Google Play Store</a>.</p>
			
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<div class="row g-5">
			        <div class="col-md-6">
						<?php
							settings_fields( 'talkie_tts_option_group' );
							do_settings_sections( 'talkie-tts-admin' );
							submit_button();
						?>
						
						<h2>See also</h2>
				           
			           <ul>
				        <li><a href="https://www.talkie-app.com/buy-me-coffee" target="_blank">Buy my coffee - &euro;3,00</a></li>
			           	<li><a href="https://www.talkie-app.com/feedback" target="_blank">Give us feedback</a></li>
			           	<li><a href="https://wordpress.org/plugins/talkie-text-to-speech/#reviews" target="_blank">Review us</a></li>
			           	<li><a href="https://www.facebook.com/talkiespeechapp" target="_blank">Facebook</a></li>
			           	<li><a href="https://www.instagram.com/talkieapp" target="_blank">Instagram</a></li>
			           </ul>
			        </div>
				</div>
			</form>
		</div>
	<?php }

	public function talkie_tts_page_init() {
		
		wp_enqueue_script('talkie-admin', plugin_dir_url(__FILE__) . '/js/admin.js');
		 
		register_setting(
			'talkie_tts_option_group', // option_group
			'talkie_tts_option_name', // option_name
			array( $this, 'talkie_tts_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'talkie_tts_setting_section', // id
			'Text to Speech', // title
			array( $this, 'talkie_tts_section_info' ), // callback
			'talkie-tts-admin' // page
		);

		add_settings_field(
			'color', // id
			'Color of button', // title
			array( $this, 'color_callback' ), // callback
			'talkie-tts-admin', // page
			'talkie_tts_setting_section' // section
		);

		add_settings_field(
			'outlined_btn', // id
			'Outlined button', // title
			array( $this, 'outlined_btn_callback' ), // callback
			'talkie-tts-admin', // page
			'talkie_tts_setting_section' // section
		);

		add_settings_field(
			'voices', // id
			'Voices', // title
			array( $this, 'voices_callback' ), // callback
			'talkie-tts-admin', // page
			'talkie_tts_setting_section' // section
		);
	}

	public function talkie_tts_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['color'] ) ) {
			$sanitary_values['color'] = sanitize_text_field( $input['color'] );
		}

		if ( isset( $input['outlined_btn'] ) ) {
			$sanitary_values['outlined_btn'] = $input['outlined_btn'];
		}

		if ( isset( $input['voices'] ) ) {
			$sanitary_values['voices'] = $input['voices'];
		}

		return $sanitary_values;
	}

	public function talkie_tts_section_info() {
		
	}

	public function color_callback() {
		
		$options = get_option( 'talkie_tts_option_name' );
		$colorValue = ($options['color']) ? $options['color'] : '#26c5e5';
		
		printf('<input class="regular-text" type="text" name="talkie_tts_option_name[color]" id="color" value="'.$colorValue.'">');
	}

	public function outlined_btn_callback() {
		
		$options = get_option( 'talkie_tts_option_name' );
		$checked = ($options['outlined_btn']) ? 'checked' : '';
				
		printf('<input type="checkbox" name="talkie_tts_option_name[outlined_btn]" id="outlined_btn" value="true" '.$checked.'>');
	}

	public function voices_callback() {
		$content = '<select name="talkie_tts_option_name[voices]" id="voices">';
			
			$options = get_option( 'talkie_tts_option_name' );
			$currentVoice = $options['voices'];
		
			if($options['voices'] != null || $options['voices'] != ""){
				$content .= '<option value"'.$options['voices'].'" selected>'.$options['voices'].'</option>';
			}
		
		$content .= '</select>';
		
		printf($content);
	}

}

if ( is_admin() )
	$talkie_tts = new TalkieTTS();
?>